### ISSUE TITLE
Duplicate Bootstrap Modals

### ISSUE THREAD

**Issue by tchompalov** [lleblanc42/jquery-userTimeout#1]
If the notification is set to a shorter interval than the actual logout, the modal will launch multiple times, causing it to layer on top of existing modals. This can be fixed with a check when launching a modal -- if it's already visible. This is an edge case -- but it will cause an issue for long session intervals.

Nice library - simple, easy to maintain.

**Comment by lleblanc42** [comment]
Thank you for your feedback! It truly means alot. I'm glad someone is using it. I'm hoping to find more time soon to progress this plugin further and fix bugs and add more features. Please submit more issues if you find anything else or have any suggestions for enhancements.

**Comment by lleblanc42** [comment]
Please pull down the latest version of the code. I wasn't able to replicate this after the recent changes. Please verify this is still an issue and then provide examples on how to properly replicate. Thank you!

**Comment by lleblanc42** [comment]
Considering I wasn't able to replicate the issue and have not gotten a response in quite some time, I'm closing this issue.
