### ISSUE TITLE
Counter Stuck

### ISSUE THREAD

**Issue by tchompalov** [lleblanc42/jquery-userTimeout#2]
When testing in Chrome the timer often fails to initialize or gets stuck. In addition, it drifts from the actual server time. This is because the library uses ,setTimeout() to count seconds, which is unreliable, as there is no promise that it will accurately fire after a given interval:

https://www.sitepoint.com/creating-accurate-timers-in-javascript/

**Comment by lleblanc42** [comment]
Thank you for your input! I'm hoping I can make some time soon to make these changes as well as others to progress the plugin further.

**Comment by mhulse** [comment]
Any chance you are going to merge this in?

**Comment by mhulse** [comment]
Ah, nvm.  I see that it is a work in progress. Ignore my last request.
