### ISSUE TITLE
Button's text property

### ISSUE THREAD

**Issue by SimonLaRochelle** [lleblanc42/jquery-userTimeout#3]
The **modalTitle** and **modalBody** are very useful to personalize the appearance of the modal form, for exemple to adapt the form to the language of the user.

We need the same option for the two button: "Log Off" and "Stay Logged In (x)".

I suggest to add **modalLogOffBtn** and **modalStayLoggedBtn** properties.

**Comment by lleblanc42** [comment]
Thank you very much for your suggestion! I haven't had much time to work on my plugins, but I will definately get to this when I can and get this merged in!
