### ISSUE TITLE
'Stay Logged In' prevents the modal from showing on subsequent timeouts

### ISSUE THREAD

**Issue by hale** [lleblanc42/jquery-userTimeout#7]
Hi and thanks for this library! I think I found a bug.

Steps to reproduce:

1. Wait for the timeout and the modal to appear. Click 'Stay Logged In' to dismiss the modal.
2. Wait for the timeout a second time.
3. Expected: the modal appears again. Actual: the logouturl is hit.

Using Bootstrap for the modal (auto detected). v0.4.0 - 2017-10-29.

Could this be because new timeouts are created on every new event when the modal is open, but only the latest is cleared?

**Comment by lleblanc42** [comment]
Thank you for your interest in my plugin! If I understand correctly, you're using v0.4 of the plugin correct? The plugin is now at v0.5.1. Make sure you're using the most up-to-date version. If I remember correctly, I pushed a fix for that with this latest release. I noticed it right after I pushed up v0.5.

Let me know if updating solves your issue.

**Comment by hale** [comment]
Thank you, yes that fixed it 🙂.

(You might want to update the `dist/` bundles to reflect the new version, I had grabbed the source from there.)
