### ISSUE TITLE
Stay Logged In Issue

### ISSUE THREAD

**Issue by jemaxson** [lleblanc42/jquery-userTimeout#9]
After clicking button to stay Logged in, after the session defined milliseconds you automatically get logged off without another modal appearing.   I'm using the latest version from GitHub as of 1/22/18.

**Comment by lleblanc42** [comment]
This is fixed, please verify. I forgot to rebuild the dist files with my last commit/merge.

**Comment by jemaxson** [comment]
Thank you. Confirmed that it is working now.

**Comment by jemaxson** [comment]
Luke,
Thanks all set.   Hey anyway to change the z-index to have the Modal display on top of another Modal?

**Comment by lleblanc42** [comment]
Sure! Please create a new issue to track it.
